Add SlNetSock modules
zephyrproject-rtos/hal_ti pull request #20
Opened 2020-08-14 22:35 UTC by vanti

Bring in SlNetSock and its associated modules from the TI CC32xx
SimpleLink SDK 4.10.00.07, with some minor tweaks to the SlNetSock
code to avoid errors/warnings when building for Zephyr, due to its
stricter build flags and its idiosyncrasies around its posix
implementations.

2020-08-17 18:48 UTC, vanti commented
@galak Updated commit message and added PR zephyrproject-rtos/zephyr#27590 for verification.

2020-08-26 21:16 UTC, vanti commented
@tbursztyka I have added a commit to revert your changes from #19 for now, so that they do not block these new changes. #19 is causing build errors when running `sanitycheck` given https://github.com/zephyrproject-rtos/zephyr/pull/24873 is not yet merged:

```
/home/vwan/zephyrproject-work/zephyr/sanity-out/cc3220sf_launchxl/samples/net/sockets/http_get/sample.net.sockets.http_get.offload.simplelink/build.log
In file included from /home/vwan/zephyrproject-work/zephyr/include/device.h:22,
                 from /home/vwan/zephyrproject-work/modules/hal/ti/simplelink/kernel/zephyr/dpl/dpl.c:12:
/home/vwan/zephyrproject-work/zephyr/include/init.h:89:11: error: initialization of 'int (*)(struct device *)' from incompatible pointer type 'int (*)(const struct device *)' [-Werror=incompatible-pointer-types]
   89 |   .init = (init_fn),     \
      |           ^
/home/vwan/zephyrproject-work/zephyr/include/init.h:136:2: note: in expansion of macro 'Z_INIT_ENTRY_DEFINE'
  136 |  Z_INIT_ENTRY_DEFINE(Z_SYS_NAME(init_fn), init_fn, NULL, level, prio)
      |  ^~~~~~~~~~~~~~~~~~~
/home/vwan/zephyrproject-work/modules/hal/ti/simplelink/kernel/zephyr/dpl/dpl.c:63:1: note: in expansion of macro 'SYS_INIT'
   63 | SYS_INIT(dpl_zephyr_init, POST_KERNEL, CONFIG_KERNEL_INIT_PRIORITY_DEFAULT);
      | ^~~~~~~~
/home/vwan/zephyrproject-work/zephyr/include/init.h:89:11: note: (near initialization for '__init_sys_init_dpl_zephyr_init2.init')
   89 |   .init = (init_fn),     \
      |           ^
/home/vwan/zephyrproject-work/zephyr/include/init.h:136:2: note: in expansion of macro 'Z_INIT_ENTRY_DEFINE'
  136 |  Z_INIT_ENTRY_DEFINE(Z_SYS_NAME(init_fn), init_fn, NULL, level, prio)
      |  ^~~~~~~~~~~~~~~~~~~
/home/vwan/zephyrproject-work/modules/hal/ti/simplelink/kernel/zephyr/dpl/dpl.c:63:1: note: in expansion of macro 'SYS_INIT'
   63 | SYS_INIT(dpl_zephyr_init, POST_KERNEL, CONFIG_KERNEL_INIT_PRIORITY_DEFAULT);
      | ^~~~~~~~
cc1: all warnings being treated as errors
modules/ti/simplelink/CMakeFiles/..__modules__hal__ti__simplelink.dir/build.make:335: recipe for target 'modules/ti/simplelink/CMakeFiles/..__modules__hal__ti__simplelink.dir/kernel/zephyr/dpl/dpl.c.obj' failed
make[2]: *** [modules/ti/simplelink/CMakeFiles/..__modules__hal__ti__simplelink.dir/kernel/zephyr/dpl/dpl.c.obj] Error 1
CMakeFiles/Makefile2:2790: recipe for target 'modules/ti/simplelink/CMakeFiles/..__modules__hal__ti__simplelink.dir/all' failed
make[1]: *** [modules/ti/simplelink/CMakeFiles/..__modules__hal__ti__simplelink.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

We can add your changes back once https://github.com/zephyrproject-rtos/zephyr/pull/24873 is ready to be merged.

2020-08-31 14:17 UTC, carlescufi requested changes
Please use the standard commit message format for imports:
https://docs.zephyrproject.org/latest/contribute/index.html#identifying-contribution-origin

2020-08-31 17:50 UTC, vanti commented
Thanks @carlescufi, good catch. Updated commit message.

2020-09-01 18:15 UTC, carlescufi approved these changes

2020-09-01 18:15 UTC, merged